##################################################################################
# This template can be used to retrive requested secrets/credentials from the Accenture HashiCorp Vault
# This template can be used to download secure file .
# Wherever needed it can be then used as a keyFile as a ref 
# $(securefiledefaultsa.secureFilePath)
##################################################################################

parameters:
- name: HASHI_ENDPOINT
  default: ''
- name: SECRET_ENV
  default: ''
- name: GCP_ROLESET_NAME
  default: ''
- name: AZ_ROLESET_NAME
  default: ''

steps:
- task: CIODevOps.hashicorp-vault-build-release-task-prd.custom-build-release-task.HashiVaultExt@0
  name: Hashi
  displayName: 'HashiCorp Vault Credentials'
  inputs:
    HashiEndpoint: ${{ parameters.HASHI_ENDPOINT }}
    return: secret
    secretEnv: ${{ parameters.SECRET_ENV }}
    engineType: gcp
    gcpRoleSetName: ${{ parameters.GCP_ROLESET_NAME }}
- task: CIODevOps.hashicorp-vault-build-release-task-prd.custom-build-release-task.HashiVaultExt@0
  name: Hashi_tf_backend
  displayName: 'HashiCorp Vault Credentials'
  inputs:
    HashiEndpoint: ${{ parameters.HASHI_ENDPOINT }}
    return: secret
    secretEnv: ${{ parameters.SECRET_ENV }}
    engineType: azure
    azureRoleSetName: ${{ parameters.AZ_ROLESET_NAME }}