###############################################################################################
# This template can be used for tf resource destruction..
# It takes input as working directory where tf files would exist.
# It also takes care of deleting composer temp buckets as well .
# It Also uses the keyFile while removing the buckets for composer.
###############################################################################################

parameters:
- name: workingDir
  default: ''

steps:
- task: Bash@3
  displayName: Terraform execution for resource destruction
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      # --------- Auxiliar Functions --------- 
      function mainHeader () {
        echo ""
        echo ""
        echo ""
        echo "***************************************************************************"
        echo " $1" 
        echo "***************************************************************************" 
      }
      
      function header () {
        echo ""
        echo "----------------------------------------------------"
        echo " $1" 
      }
      
      
      function message () {
        echo "$1"
      }
      
      function setValue () {
        echo "> $1"
      }
      
      function footer () {
        echo ""
        echo "----------------------------------------------------"
        echo ""
        echo ""
      }
      
      function mainFooter () {
        echo "" 
        echo "***************************************************************************"
        echo ""
        echo ""
        echo ""
      }
      
      
      ls $(System.DefaultWorkingDirectory)
      echo "________________________"
      
      mainHeader "Terraform - Init + Plan"
      
      footer 
      
      header "Terraform.tfvars file content"

      echo $(Hashi_tf_backend.AzClientID)
      echo $(Hashi_tf_backend.AzClientSecret)

      export GOOGLE_APPLICATION_CREDENTIALS=$(GCP_CRED)
      export ARM_CLIENT_ID=$(Hashi_tf_backend.AzClientID)
      export ARM_CLIENT_SECRET=$(Hashi_tf_backend.AzClientSecret)
      export ARM_TENANT_ID=$(TENANT_ID)
      
      tfVarsFileName=tokenized.terraform._tfvars
      
      setValue "File terraform.tfvars content: "
      cat $tfVarsFileName
      echo ""
      footer
      
      header "Terraform - Init"
      terraform init
      footer
      
      header "Terraform - Plan"
      terraform plan -input=false -var-file=$tfVarsFileName
      footer
      
      terraform output -json > output.json
      
      header "Terraform - Destroy"
      terraform destroy -auto-approve -input=false -var-file=$tfVarsFileName

      ################## CHECKING RET CODE ##############
      ret_code=`echo $?`
      if [[ "$ret_code" -eq 1 ]]; then
          echo "Some issue occured while resource destruction ... please check logs."
          exit 1
      fi
           
      footer
      
      mainFooter
    workingDirectory: ${{ parameters.workingDir }}